version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-cartelesleizaran
    environment:
      MARIADB_DATABASE: cartelesleizaran
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ${DB_DATA_INI_FILE}:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mysql-client:
    image: mysql:8
    container_name: mysql-client
    depends_on:
      - mariadb
    entrypoint: ["sleep", "infinity"]
    # Para entrar al cliente:
    # docker exec -it mysql-client mysql -h mariadb -u root -p
    networks:
      - default

  cartelesleizaran:
    build: .
    container_name: cartelesleizaran
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: cartelesleizaran
      PORT: ${PORT}
    ports:
      - target: 3000       # Inner (Container)
        published: ${PORT} # Outer (Host)
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
